version: '3.8'
services:

  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - neo4j
      - postgres
    networks:
      - network
    links:
      - neo4j
    environment:
      NEO4J_BOLT_URL: 'bolt://$NEO4J_USER:$NEO4J_PASSWORD@neo4j:7687'
      DJANGO_SETTINGS_MODULE: 'tripper.settings'
    env_file:
      - .env

  neo4j:
    image: neo4j:4.4.6
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - network
    volumes:
      - neo4j_data:/data
    environment:
      NEO4J_AUTH: $NEO4J_USER/$NEO4J_PASSWORD

  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  db: {}
  neo4j_data: {}