version: '3.8'
services:

  backend:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    depends_on:
      - neo4j
      - postgres
    networks:
      - network
    links:
      - neo4j
    environment:
      NEO4J_BOLT_URL: 'bolt://$NEO4J_USER:$NEO4J_PASSWORD@neo4j:7687'
      DJANGO_SETTINGS_MODULE: 'tripper.settings'
    env_file:
      - .env
    volumes:
      - static_files:/app/static

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - static_files:/app/static
    ports:
      - "9000:9000"
    depends_on:
      - backend
    networks:
      - network

  neo4j:
    image: neo4j:4.4.6
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - network
    volumes:
      - neo4j_data:/data
    environment:
      NEO4J_AUTH: $NEO4J_USER/$NEO4J_PASSWORD

  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  db: {}
  neo4j_data: {}
  static_files: {}